# TBESC TO 1 Data Quality Report

## Enrollment Progress
---------------------
```{r,echo=FALSE, results="hide",message=FALSE, warning=FALSE,error=FALSE}
library(to1check)
library(plyr)

# Load the latest cleaned data
load("G:\\StrategicArea\\TB_Program\\Research\\TBESC 2\\Data\\cleaned\\to1clean.rdata")

# Set aside those who were successfully enrolled - we'll generally disregard those who declined
# or didn't complete enrollment 
enrolled <- to1clean$master$StudyId[to1clean$master$CloseReason %in% c("Triple Negative", "Open")]
```

Total Enrollment To Date: `r nrow(subset(to1clean$master, VisitDate >= as.Date("2012-11-01")))`

(excludes enrollment prior to November 2012 - assumed to be pilot enrollment)


```{r,echo=FALSE, results="hide",message=FALSE, warning=FALSE,error=FALSE,fig.width = 12, fig.height = 6}
# Plot enrollment progress to date
enrolled_dates <- to1clean$master$VisitDate[to1clean$master$StudyId %in% enrolled]

enroll_progress_plot(enrolled_dates,
                     target = 500,
                     enroll_start = as.Date("2012-11-01"),
                     enroll_end = as.Date("2013-08-30")
)

```

### Participants by Status




### Participants by Country of Origin
```{r,echo=FALSE, results="hide",message=FALSE, warning=FALSE,error=FALSE,fig.width = 8, fig.height = 8}

# Tally up participants by their country of birth
birthco <- arrange(count(to1clean$master, var = "BirthCountry"), freq, BirthCountry)

# BirthCountry == "" indicates a pre-enrolled person
birthco$BirthCountry[birthco$BirthCountry == ""] <- "Pre-enrolled"

# Make BirthCountry a factor - this ensures descending order of the bars
birthco$BirthCountry <- factor(birthco$BirthCountry,  levels = birthco$BirthCountry)



# Plot it
ggplot(birthco, aes(x = BirthCountry, weight = freq)) +
  geom_histogram() +
  coord_flip() +
  labs(title = "Enrollment by country of birth",
       x = "Country of Birth",
       y = "Number Enrolled")

```




### Participants by Language




### Testing Results




## Participants with Action Needed
-----------------------------------

### Participants Eligible for Follow-Up
```{r,echo=FALSE,results='asis',message=FALSE, warning=FALSE,error=FALSE}
fu_report <- calc_fu(to1clean)

names(fu_report) <- c("StudyID", "Enroll Date", "FU Starts", "Fu Ends", "Eligible for FU",
                      "FU Cycle", "Days Left", "Completed")


if(nrow(fu_report) > 0) {
    cat(paste(names(fu_report), collapse = " | "), 
        paste(rep("---", length(names(fu_report))), collapse = " | "),
        sep = "\n"
    )
    cat(apply(fu_report, 1, function(x) paste(x, collapse = " | ")), sep = "\n")
} else {
  cat("No participants require follow-up at this time.")
} 
```


### Participants with Undocumented Treatments

### Triple-Negative Participants to Close
```{r,echo=FALSE,results='asis',message=FALSE, warning=FALSE,error=FALSE}
tripnegtoclose <- closed_check(to1clean)

if(nrow(tripnegtoclose) > 0) {
    cat(paste(names(tripnegtoclose), collapse = " | "), 
        paste(rep("---", length(names(tripnegtoclose))), collapse = " | "),
        sep = "\n"
    )
    cat(apply(tripnegtoclose, 1, function(x) paste(x, collapse = " | ")), sep = "\n")
} else {
  cat("All triple-negative participants are closed.")
}
```

## Data Quality Checks
------------------------

### Participants with TSTs Read Outside of the 44-76 Hour Window



### Participants with Missing TST, QFT, or TSPOT Results
```{r,echo=FALSE,results='asis',message=FALSE, warning=FALSE,error=FALSE}
# Identify participants with a missing test
testres <- compile_results(to1clean)

missingtest <- subset(testres,
                      subset = (is.na(tst) | is.na(qft) | is.na(tspot)) & StudyId %in% enrolled,
                      select = c("StudyId", "tst", "qft", "tspot"))

names(missingtest) <- c("StudyId", "TST Result", "QFT Result", "TSPOT Result")

if(nrow(missingtest) > 0) {
    cat(paste(names(missingtest), collapse = " | "), 
        paste(rep("---", length(names(missingtest))), collapse = " | "),
        sep = "\n"
    )
    cat(apply(missingtest, 1, function(x) paste(x, collapse = " | ")), sep = "\n")
} else {
  cat("All participants have TST, QFT, and TSPOT test results.")
}
```


### Height and Weight


